### ISSUE TITLE
代码运行

### ISSUE THREAD

**Issue by Wuhuddy** [wuyang98/cvpr_2023_submission#2]
你好，运行coseg_test.py时出现以下报错：
![image](https://github.com/wuyang98/CoSOD/assets/121659356/4da19a80-f616-47cd-8400-32e3fccea7fa)
请问如何解决，以及训练时代码运行顺序应该是怎样的呢？

**Comment by wuyang98** [comment]
你好，感谢你对我们工作的关注。在训练阶段，需要先训练vqvae，然后固定住vqvae训练pixelcnn，最后进行整个模型的训练，训练过程中vqvae权重为冻结状态，pixelcnn权重为未冻结状态。整理好的代码和readme将在不久后更新。

**Comment by Wuhuddy** [comment]
![image](https://github.com/wuyang98/CoSOD/assets/121659356/1c027813-6f3c-4c6c-8c2a-577f104073df)
你好，请问dateset.py的这块代码中contour是什么数据？我在训练过程中报错找不到这个目录。

**Comment by wuyang98** [comment]
你好，contour是二值化标签的边缘信息，可以使用draw_contour.py为数据集中的二值化标签提取边缘信息，并用于训练。同时，也可以对代码进行修改，以不使用边缘信息，默认是使用的。

**Comment by Wuhuddy** [comment]
好的我明白了，感谢回复
